# Generated by Django 3.1.3 on 2020-12-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.jpeg', upload_to='avatar/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
    ]
