version: "3.7"

services:
  web_1:
    build: .
    command: python manage.py runserver 0.0.0.0:5001
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5001:5001
    depends_on:
      - db
    env_file:
      - ./.env-admin.prod
#  web_2:
#    build: .
#    command: python manage.py runserver 0.0.0.0:5002
#    volumes:
#      - ./:/usr/src/app/
#    ports:
#      - 5002:5002
#    depends_on:
#      - db
#  web_3:
#    build: .
#    command: python manage.py runserver 0.0.0.0:5003
#    volumes:
#      - ./:/usr/src/app/
#    ports:
#      - 5003:5003
#    depends_on:
#      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=askme_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=askme_db
    ports:
      - 5432

volumes:
  postgres_data:
