version: "3.3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - ./.env-admin.prod
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=askme_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=askme_db
    ports:
      - 5432

volumes:
  postgres_data:
